export default function AboutPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold text-slate-900">About this demo</h1>
      <p className="mt-3 text-slate-600">
        A reference build that demonstrates an end-to-end Epic Clarity → Snowflake → dbt → React data
        pipeline. The source is an Epic Clarity-shaped SQL Server instance on AWS EC2; Fivetran's
        SQL Server CDC connector mirrors changes into Snowflake; dbt builds staging, intermediate,
        and mart layers; a Python script exports the marts to JSON and a static React SPA serves
        the user-facing experience.
      </p>

      <section className="mt-10">
        <h2 className="text-xl font-semibold text-slate-900 mb-3">Data sources</h2>
        <div className="space-y-3">
          {DATA_SOURCES.map((s) => (
            <article key={s.title} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
              <h3 className="font-semibold text-slate-900">{s.title}</h3>
              <p className="mt-1 text-sm text-slate-600">{s.description}</p>
              {s.note && <p className="mt-2 text-xs text-slate-500">{s.note}</p>}
            </article>
          ))}
        </div>
      </section>

      <section className="mt-10">
        <h2 className="text-xl font-semibold text-slate-900 mb-3">Architecture</h2>
        <div className="space-y-3">
          {STEPS.map((s) => (
            <div key={s.name} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
              <div className="flex items-start gap-4">
                <div className="h-10 w-10 rounded-lg bg-brand-100 text-brand-700 flex items-center justify-center font-bold shrink-0">
                  {s.icon}
                </div>
                <div>
                  <div className="font-semibold text-slate-900">{s.name}</div>
                  <p className="mt-1 text-sm text-slate-600">{s.desc}</p>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {s.tags.map((t) => (
                      <span key={t} className="text-[11px] font-medium uppercase tracking-wider text-slate-500 bg-slate-100 px-2 py-0.5 rounded">
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-10 rounded-xl bg-amber-50 border border-amber-200 p-5 text-sm text-amber-900">
        <strong>Disclaimer:</strong> All patient data shown is synthetic, generated for demonstration
        purposes. The schema is modeled after Epic's Clarity reporting database but contains no
        real Protected Health Information (PHI).
      </section>
    </div>
  );
}

const DATA_SOURCES = [
  {
    title: 'Epic Clarity (SQL Server on EC2)',
    description:
      "An EC2-hosted SQL Server instance with a synthetic Epic Clarity schema: patient, pat_enc, pat_enc_dx, hsp_account, hsp_transaction, providers, departments, and more.",
    note: 'Provisioned via Terraform in infra/. Synthetic data generated by scripts/generate_data.py.',
  },
  {
    title: 'Fivetran SQL Server CDC connector',
    description:
      'Mirrors every change in the source SQL Server (inserts, updates, deletes) into Snowflake on a configurable schedule. Schema name lands as JASON_CHLETSOS_EHR_DEMO.',
  },
  {
    title: 'Snowflake — destination',
    description:
      'Database JASON_CHLETSOS_EPIC holds the raw landing schema and the dbt-built marts. Warehouses are split into a transform warehouse for dbt and a query warehouse for the API layer.',
  },
];

const STEPS = [
  {
    icon: '1',
    name: 'Fivetran — Ingestion',
    desc: 'CDC connector replicates SQL Server Clarity tables into Snowflake without writing custom ETL.',
    tags: ['SQL Server CDC', 'Incremental sync', 'Schema discovery'],
  },
  {
    icon: '2',
    name: 'Snowflake — Storage & compute',
    desc: 'Raw tables land in a dedicated schema; dbt builds staging / intermediate / marts on separate warehouses.',
    tags: ['Snowflake', 'Role-based access', 'Separate WH'],
  },
  {
    icon: '3',
    name: 'dbt — Transformation',
    desc: 'Tested SQL builds dim_patients, dim_providers, dim_departments, fct_encounters, fct_diagnoses, fct_account_summary.',
    tags: ['Dimensional model', 'dbt tests', 'Documentation'],
  },
  {
    icon: '4',
    name: 'React + Recharts — Public portal',
    desc: 'Static SPA reads daily JSON exports of the marts. No backend required at request time.',
    tags: ['React 19', 'Recharts', 'GitHub Pages'],
  },
];
